apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/Timo-Weike/home-cluster.git
      targetRevision: main
      path: charts/keycloak
      helm:
        releaseName: keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
