apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: "22.x.x"
      helm:
        valueFiles:
        - values.yaml
    - repoURL: https://github.com/Timo-Weike/home-cluster.git
      targetRevision: main
      path: cluster/components/keycloak/more
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true