apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  # Adjust the addresses to your LAN
  addresses:
    # - 192.168.8.16-192.168.8.250
    - 192.168.1.1-192.168.1.254
