

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    pgadmin-password: AgBYFMTVWR0v+bHfuUBdb4lfVix7ab2J8Aj3mZg3ZKF1VMdU4CdMJ3QfRH/y8jOd1R8gAJl+vxH3vsUxurm588TpfODiIPN13objljLWvM8SPCJ43TFro5S0L+fCCBlo1UOWjp5DpWJcZXNl96RUKv6PSCstz3UhUyP8tyTzOg/N8s9UwB+5Yn9L7mpF9b/PL3rYVPDuB/pck0kb1BGAPAWC/RXxr1/vxh551tJAat2SAD6k0MH9/uhKwqB2EsaMgZTFs5DAf+HQF/669u4oSUyCE1/qlNmsHQmudts/cK1Qpsvv4qzXnIxfru95shVjOc0vIBp/nLbkoLc2WpVPYK7vmX3UhM3u8JBRJm8dIMTdQjBMijEW5trJSZtfY8Bc8Guu+6j4Ri0byIjeFPPxRW0UOQJGXPQJaut0JNk7Ubm4NCEnDo7wOiWiovlACshb8EeOmdTusTBshaHrUO1ylyyg0JgjGWZcuS10+kqyTAX8xr0rwm3jWghRELLddlTE+czDYJWv9sznljYUWgaC61W1XuS635UHOTme6CReQzegPLwFLMcmCOUdbaqwYpi4VCEUaRi8aDYCcUnfEazCr3XMQwT39SzFpJXEkz6AM1fvDOMKfkVJQL1H/2AGNp34JnIUX9nVok2WnK+9sDMGySZIjp8CkFqtj3wc5qN5CiLT3fHeBqiw8ncCkQVM+hIllDrbTssUvc7kbkJitdt5T26KmKS7CqVx6+QE2n1WhpHW1JwQvRkScmZeRto5WKLFhW3JaA==
  template:
    metadata:
      name: pgadmin-secret
      namespace: {{ .Release.Namespace }}
---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgCi9oHQZ2BFfST00cBacLXljy79oclsgSoRHvCMiJYN8Iqi3xWtxt8oeYEhIYfp85+bt+CtptK9JglXlTMSVo5bP3WJiT/arVLy5iU8o6n+11RlL0aI33NItCAPwVpeKgd++DDRnnsuPtr/m87c+frUyKKSo9nilWUDxymr4KsL4f26+WUnFyLVh512aM04TxYMXoNZU45mi6DdlR5urCqwotvRcVqDwOK0ZC5TfFTQJ73FYjzV0xjcW/p9sEgmS1MQ6jNqtS3X4I6fH6sZKgAe80hlzBWpzptQlVUvoRuzfAUtsuDMxy2GzDQjUlhoIHX0lQKmQUNKCBDYOpU4odjcd7LPD5nu/P2uq1N5dZcraRXVsabAZMYZRd9vStPmpc4U5edUNmOW3IcXqTFy0CoJs3MIjDW8E6PLhl+duc1mWBuKObIL4B5+z6wgc4JDJyJ7+HK0YpavNc05PDHnUwnxxaGxFnNDIvpz85p/6fL9J4furFqgO2kz+oRvqIEwlCupdPGOaoqsPm0wswTPqBo+Zdz9srrkNbCYkqAQYrWWWfdaqzin6lpnzkQeIHLwekcFj0bwI9WPeD+tSEuVwrHJbgvbrxHzHd33s771YUaG0OE5+OXoqJGz6PDatu1mLHs+5NUlPkwKCSKKQsdXw6PntwOaLJ3/FWDi78CZ9jVzUEoN8cP35bDPl2Ml3q6C3PJy724VzZmnctZg/TkrApyJTc94wVheMxUhqY2gWe5mJosxqZGt/i67t2gJgFfyVb/ESg==
  template:
    metadata:
      name: postgres-credentials
      namespace: {{ .Release.Namespace }}
---