

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "postgres-stack.fullname" . }}-pgadmin-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    pgadmin-password: AgCymBdqjh8XPFBrsAfnTd7Li6RCy6Zgxm5trI7v3iS3nSE8pqWO1WIbTvr8R7H4DufwfvfokNAOYtGu143N6zzHt+78+SHOQ/fE87Mlq1jpWRVuDjNC+S45tAIWuhvHhlqq7/NqwmfUkQaDq8SrzFsYOxd34bOSCws0/9nzolx9fEZdYSp59Za1XZV3wa/s5aTmwFOsWKWTyOlm/zz9rfJCHhgC9AZh08LWSqjhAO/yzV6IluR3UCZMdi0qDkQp8Eewr98wwSC6XnfQoCiwd/6J5Fxa2DM/rAbcJ1UwxPBckDhifike5OgFRhAToU7dxh2nfceNhmk7TcxfGXf53OmQKTU20oHMkOrBmztqkiUqfremHYfYR8vzEnXfVqlOTjxFivrDZevykRW/oTSTvzZ4/gp7sXQFcO1pMMiARNhL43MpaDvjPGvl+jH5tW3QxZxCtD0UWaWrhUlSpbdz9EL+OVPhP10O/Zam2HjZbk9J9AVxqZnnqZjOrx8Hf8tfWLW9dq0Q9aAE+9YjFg9cAfk6Ng0o5SZBruB/qbrCtnnEwnCizgDqZEV2rnW6e5UqTdlVoQ/ly6KkBSjhNe/U05c/zSzDbVWhE0kuKSgWRDi4sxFIN4H4v6HWS+lPIAasC9tPNtfq8ryDJQdh5r359HsQzHTSJB/UVEkAMMWaZOr3MKIx07bLn1MO0SWK+ySUQcejELh6OW2mxT/K5rRDce99pC1zIr569rrHfXIH4JNRwZNKoF8cWrPXhuyH0f4GGOD0XQ==
  template:
    metadata:
      name: pgadmin-secret
      namespace: {{ .Release.Namespace }}
---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgB2kinaPqTvYeoaYXVjgYtcnvm1/VDjFOqOwFM8t8hNtvgfPUARKBkisu/r+i2P9Li0eevlITyTA/l6zIysaa+kTo0+AiQeMkByXjWSJ1vGtzcW5lXuOjCFDcmAVPh46wg4y97Bn4TSb9C3VeyjtFxJ3eRj0GvBDo4eRKv8Xp6uhm/JO2vd4643G2p85T5tEL3VseHNfK2nZD+bMiqKMFGSdziKDdofyrVXX8cyPczuKKeE8CVehpZMt/W5qY6CAlPgD7emdjDcea/blXQPAWmFCPPVmFWluv3OgQJJQqNXa5qxSrProGDtRHsChID+WyGokxxwos+uxd2NRQeJ+icTOGfgpbCcV6Pkll8fj6+GYQ/eSQjBX4nkZ9gSigM0NLDjCuSRZLrCuQ97gRmDKXqx4nK2L7QMloZJNNYkLStKHKmU8Kzm6+JIPRqfD6HqxaEw4DhfVqevmxD6Lhc3Y8om4gpt4F5TzEtYOsVT/MywKSUrHbhlA63iinWFahSPdSuys1cJ5iEHP0ru9NB3ec+We86Kq6zPKTg6aScxuL77rIOGoWvBSM3s8w+hTtigwu1duyucqK1mEKiHHGau0dgkYo4qeNXCRBQMBYnuEKtCtbMODdjw7lE0sNdu82L+oUo9Q06S5aybk9Nkj1ZDxCkCuLiXclqY/H+PZ0MBKSbFNKEd+ohcUK5N5mj7CN7Q8qh27ZuJupm+W4JaeF9Ghp/1CbX+h5VaJ0Dz0QDo8VXWDuzps85EVTUOj3vCZkvFDlzn3Q==
  template:
    metadata:
      name: postgres-credentials
      namespace: {{ .Release.Namespace }}
---