apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCfokJAQ36rycaRdQS2hpAFwOqQrQpGmAN2Xwf6nRxQIooQarK7Krh8X789TiBwgujeb4aJrLKtV58LOQ8X+Wewle75tf+Rm9kT3vqZcEMnRLsKrKMETt/QuBRrXmHRb4jzcE6FTGf/yAftU0S8BfUToqsrbOqaAlfKwsMyK023wJsn751rGVpsTtei3Heu4cxNF3A5jY6uhEUcC6LrCnYcf9QdbYp3YUVK0sIe/1omg5ALlWi1ky62Eg33a2iHlUoRcrC/olutgjL5f0n4qtQYvdiRy9CHakCzxcFzv0Ad0qc+1yxBX2AMlQG4vvR5JtiaRiQd2LuTZ8uTeuz0rD/YXuNTuUiRnIXHICBASx4DSLqrh0VQ0NyX8zewIZJXhil7n+rCFddqhE1Qq6F4lnCkT24iKPgxzmh+apWjlaxmG0up9MFrSAh7ei3Yo3fyeuzMATtz9gqOS/Nk6GfLdtKDxGPo9+mdDKIEX4Xpzqm2pfEnIiEyxE5LTNvpFLrq8EHXBkJlM/EgxJ5LzbhS/wrkNJThW37biybU+gaBSpoUgDUQhR/LuavPSu/bHqLxFRet4u9NLaud3wQyV1YpjrvAuwy2nmiYr0fRLKUe661IEYQpbdrFV/bjQoD2941ONx+ZLyW3Rm9uAplNky9Uf4PA3qwhsTSnYN+stQ2T8AS8DU2cAFUcL011tqS8ea2BGzUq49gzSETATvHGl1CKd1GmfLUADXhiVzMaxXZR2uAX3A9J9YzRn1ibCTw=
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak