apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    # Generate with:
    # echo -n 'your-db-password' | kubeseal --raw --from-file=/dev/stdin \
    #   --namespace keycloak --name keycloak-db-secret
    db-password: AgCOxIXdaajd2RiGoMi7kGO3s/Xv+ou/MtTgN2mX2HMwLjGt+RBB8Lsp0mT24bvVBzE8Nr7i3P6YqP3EywMyfIW6qyqAaVCcEy17L4orDyr11EWtWGiB0hIH38s/mvKkHk7vNhfsfdVcHF8eGv73NM2+KanhI1RXSnqQqZrtKHsTkG8DGxiIEro9S+KUpVG8Qj58NwdMmQ9AJ3Io9Gh2MkjBlZNXiQIZFsXEQJDRrCHI98buMp7K0zMNv1zcKpPivMZh2pvAkwDMto6vcfMfp5nDptW3LTbOy0WmgvZJumCZkzq92HuKztOz8mxHYYJM12GmvAFaEBgkMJ1ACyNvRn8rzEpSeEf7uwKqdca57VZDp5APkgeD+gexpnjyMSmS0LmWlsiuR+ogWcPmhKXpQyqEe7o7BjL17/T1kVRwZwYJlRl76Kwt4gmx+1gArSndf7vQH/H82VYu0DSMblRQvfa8RL2yaJ+WixLhnkGkf+UD5kwsHeZTV1jnyvKTTqPhw5/86jWK9EZPm4ZzR4Tzf+DBJtll0uSM+Cc5JIGsXoeXEkclMc+BAaun46LsxS9rMoIgi2TkCRwGIxcD3Gqvzy/wGB19tPVdpKNYPsnxrazZQ1cJUExTd2CcMqnQp3ftC54WoW9I8baDxbJ+CD4rTESPoeFqFtZjTPwL7S/+7r9fitffs8lE7nllJH0msPUfpnqUbYMFUAt5h9UhzcEKwo1iB9TR
    db-admin-password: AgCOxIXdaajd2RiGoMi7kGO3s/Xv+ou/MtTgN2mX2HMwLjGt+RBB8Lsp0mT24bvVBzE8Nr7i3P6YqP3EywMyfIW6qyqAaVCcEy17L4orDyr11EWtWGiB0hIH38s/mvKkHk7vNhfsfdVcHF8eGv73NM2+KanhI1RXSnqQqZrtKHsTkG8DGxiIEro9S+KUpVG8Qj58NwdMmQ9AJ3Io9Gh2MkjBlZNXiQIZFsXEQJDRrCHI98buMp7K0zMNv1zcKpPivMZh2pvAkwDMto6vcfMfp5nDptW3LTbOy0WmgvZJumCZkzq92HuKztOz8mxHYYJM12GmvAFaEBgkMJ1ACyNvRn8rzEpSeEf7uwKqdca57VZDp5APkgeD+gexpnjyMSmS0LmWlsiuR+ogWcPmhKXpQyqEe7o7BjL17/T1kVRwZwYJlRl76Kwt4gmx+1gArSndf7vQH/H82VYu0DSMblRQvfa8RL2yaJ+WixLhnkGkf+UD5kwsHeZTV1jnyvKTTqPhw5/86jWK9EZPm4ZzR4Tzf+DBJtll0uSM+Cc5JIGsXoeXEkclMc+BAaun46LsxS9rMoIgi2TkCRwGIxcD3Gqvzy/wGB19tPVdpKNYPsnxrazZQ1cJUExTd2CcMqnQp3ftC54WoW9I8baDxbJ+CD4rTESPoeFqFtZjTPwL7S/+7r9fitffs8lE7nllJH0msPUfpnqUbYMFUAt5h9UhzcEKwo1iB9TR
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak