apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    # Generate with:
    # echo -n 'your-admin-password' | kubeseal --raw --from-file=/dev/stdin \
    #   --namespace keycloak --name keycloak-admin-secret
    admin-password: AgBe5rbkLvTwAnbe3EGmxSUkBuY4ff8d8j/QwkWQYtuFlDdO2ZemDn7pMbgvbQ942I/8Xw3UZu4FgUaWU3zvDxGaN+JzSLZuoxk00jzrTPXNdmcSUwtnTyvOwgDGnvAgT465AAr55U2L2zegIr75r514wrBf/Q5wsP3TH6RhSs0stEEaQrV7uP1J33GRpPC9EuxTW7yrKlZ95jVkRsRx+IOlBmxkHXmVJQGhcYMy1x09lQS3LmjHzymVqC6EOk5g393e1TZPBI/SGZ/PUHPrHw84+h38IBYZit57q1S7/EJ5xQCpaPBjoOmnQ4ZoD80JVjtaIcP7UpAF6ox0AlEUDGyNOOlvFS4vxQMKMpA7nRGL11+RcFKByZJ06YeeNpKE4NErZvnxhfdMv29jG10/cTrDLDDlzBn+RI4TQivQjT0uzny/ytHP/WThwmNWAlj4Ec/0y0L2vFK11QItTdar91LR77hn6t1czIAGbS8FwZz0OOH5YGKLybzLh3rgzD34nM2yiliL17uUsz7pTXzzuq0raJ0mOq5hHEMOVyrS4Ur64lRX7H91hyQqbYq2c2/UXJG1/YeCEd4OTgBQ8N06wVjzkJ4w1huHJdmTtx4DUGJeSIq7A6RBqkfADZ6cJccAskESOPFVWYGaGiAXNuP52dFLcgz/1N4xbWwL2MiDE+vHdZSS2m4ZkaVBiOH6ud4MmNXYbaDX/N4WgH/g9eulUQ21paeC
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak