apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultReplicaCount: 3
            storageOverProvisioningPercentage: 200
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
