# Longhorn helm installation as a HelmChart manifest
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart: https://charts.longhorn.io/longhorn-1.4.0.tgz
  targetNamespace: longhorn-system
  valuesContent: |
    defaultSettings:
      defaultReplicaCount: 3
      storageOverProvisioningPercentage: 200
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
