apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components-metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mariano-italiano/argocd-apps
    path: cluster/components/metallb
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true